# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-10 16:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custommail', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='classifications',
            field=models.CharField(choices=[('Unread', 'Unread'), ('Read', 'Read')], default='Unread', max_length=200),
        ),
    ]
