# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custommail', '0002_mailbox_classifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mailbox',
            name='date',
        ),
        migrations.AlterField(
            model_name='mailbox',
            name='classifications',
            field=models.CharField(choices=[('Read', 'Read'), ('Unread', 'Unread')], default='Unread', max_length=200),
        ),
    ]
