# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-16 21:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custommail', '0003_auto_20170212_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 2, 16, 21, 15, 10, 470443)),
        ),
    ]
