# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('posts', models.CharField(max_length=200)),
                ('statement', models.TextField()),
                ('picture', models.FileField(upload_to='uploads/staff_members')),
            ],
        ),
    ]
