# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner_image', models.FileField(upload_to='uploads/home_banner')),
            ],
        ),
    ]
