# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-26 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_home_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classifications', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='products_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('caption', models.TextField()),
                ('image', models.FileField(upload_to='uploads/products_image')),
            ],
        ),
        migrations.CreateModel(
            name='services_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('banner_image', models.FileField(upload_to='uploads/services_banner')),
            ],
        ),
    ]
