# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-03 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_products_products_display_services_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products_display',
        ),
        migrations.AddField(
            model_name='products',
            name='caption',
            field=models.TextField(default='null'),
        ),
        migrations.AddField(
            model_name='products',
            name='product_thumbnail',
            field=models.FileField(default='null', upload_to='uploads/products_image'),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(default='null', max_length=200),
        ),
        migrations.AlterField(
            model_name='products',
            name='classifications',
            field=models.CharField(choices=[('Web', 'Web'), ('App', 'App'), ('Graphics', 'Graphics')], default='Select', max_length=200),
        ),
    ]
